Repository VictorHarri-Chal/R-Type, pull requests merged in 2022-10, with the labels that each got.

#56 [UPD] move fonction from iscreen to world
  src/client/game/Game.cpp
  src/client/game/Game.hpp
  src/client/screens/IScreen.hpp
  src/client/screens/intro/IntroScreen.cpp
  src/client/screens/intro/IntroScreen.hpp
  src/client/screens/menu/MenuScreen.cpp
  src/client/screens/menu/MenuScreen.hpp
  src/client/screens/multiplayer/MultiplayerScreen.cpp
  src/client/screens/multiplayer/MultiplayerScreen.hpp
  src/client/screens/options/OptionsScreen.cpp
  src/client/screens/options/OptionsScreen.hpp
  src/ecs/world.cpp
  src/ecs/world.hpp
  src/server/main.cpp
Labels: architecture

#57 Feature/53 add message queue
  CMakeLists.txt
  src/server/main.cpp
  src/server/network/SafeQueue.cpp
  src/server/network/SafeQueue.hpp
Labels: network

#70 [MRG] create-releases branch into main
  .github/workflows/build-and-release.yml
  .github/workflows/build.yml
  .github/workflows/mirror.yml
Labels: devops
